---
# Source: terraria/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: terraria-world-1
  labels:
    app.kubernetes.io/name: terraria-world-1
    helm.sh/chart: terraria-0.4.0
    app.kubernetes.io/instance: terraria
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
data:
  config.json: |
    {"AllowAllowedGroupsToSpawnBannedItems":false,"AllowCorruptionCreep":true,"AllowCrimsonCreep":true,"AllowCutTilesAndBreakables":false,"AllowHallowCreep":true,"AllowIce":false,"AllowLoginAnyUsername":true,"AllowRegisterAnyUsername":true,"AnnounceSave":true,"AnonymousBossInvasions":true,"ApplicationRestTokens":{},"AutoSave":true,"BCryptWorkFactor":7,"BackupInterval":0,"BackupKeepFor":60,"BanOnHardcoreDeath":false,"BanOnMediumcoreDeath":false,"BroadcastRGB":[127,255,212],"ChatAboveHeadsFormat":"{2}","ChatFormat":"{1}{2}{3}: {4}","CommandSilentSpecifier":".","CommandSpecifier":"/","DefaultGuestGroupName":"guest","DefaultMaximumSpawns":5,"DefaultRegistrationGroupName":"default","DefaultSpawnRate":600,"DisableBuild":false,"DisableClownBombs":false,"DisableDungeonGuardian":false,"DisableHardmode":false,"DisableInvisPvP":false,"DisableLoginBeforeJoin":false,"DisableSecondUpdateLogs":false,"DisableSnowBalls":false,"DisableSpewLogs":true,"DisableTombstones":true,"DisableUUIDLogin":false,"DisplayIPToAdmins":false,"EnableBanOnUsernames":false,"EnableChatAboveHeads":false,"EnableGeoIP":false,"EnableIPBans":true,"EnableTokenEndpointAuthentication":false,"EnableUUIDBans":true,"EnableWhitelist":false,"ForceHalloween":false,"ForceTime":"normal","ForceXmas":false,"HardcoreBanReason":"Death results in a ban","HardcoreKickReason":"Death results in a kick","HardcoreOnly":false,"HashAlgorithm":"sha512","HealOtherThreshold":50,"IgnoreChestStacksOnLoad":false,"IgnoreNoClip":false,"IgnoreProjKill":false,"IgnoreProjUpdate":false,"InfiniteInvasion":false,"InvasionMultiplier":1,"KickEmptyUUID":false,"KickOnDamageThresholdBroken":false,"KickOnHardcoreDeath":false,"KickOnMediumcoreDeath":false,"KickProxyUsers":true,"LogPath":"tshock","LogRest":false,"MaxDamage":1175,"MaxHP":500,"MaxMP":200,"MaxProjDamage":1175,"MaxRangeForDisabled":10,"MaxSlots":8,"MaximumLoginAttempts":3,"MediumcoreBanReason":"Death results in a ban","MediumcoreKickReason":"Death results in a kick","MediumcoreOnly":false,"MinimumPasswordLength":4,"MySqlDbName":"","MySqlHost":"localhost:3306","MySqlPassword":"","MySqlUsername":"","PreventBannedItemSpawn":false,"PreventDeadModification":true,"PreventInvalidPlaceStyle":true,"ProjIgnoreShrapnel":true,"ProjectileThreshold":50,"PvPMode":"normal","RESTLimitOnlyFailedLoginRequests":true,"RESTMaximumRequestsPerInterval":5,"RESTRequestBucketDecreaseIntervalMinutes":1,"RangeChecks":true,"RegionProtectChests":false,"RegionProtectGemLocks":true,"RememberLeavePos":false,"RequireLogin":true,"ReservedSlots":20,"RespawnBossSeconds":10,"RespawnSeconds":5,"RestApiEnabled":true,"RestApiPort":7878,"RevertToTextLogsOnSqlFailures":10,"SaveWorldOnCrash":true,"SaveWorldOnLastPlayerExit":true,"ServerFullNoReservedReason":"Server is full. No reserved slots open.","ServerFullReason":"Server is full","ServerName":"andrew","ServerPassword":"","ServerPort":7777,"ShowBackupAutosaveMessages":true,"SpawnProtection":true,"SpawnProtectionRadius":10,"StatueSpawn200":3,"StatueSpawn600":6,"StatueSpawnWorld":10,"StorageType":"sqlite","SuperAdminChatPrefix":"(Admin) ","SuperAdminChatRGB":[255,0,0],"SuperAdminChatSuffix":"","TileKillThreshold":60,"TileLiquidThreshold":15,"TilePaintThreshold":15,"TilePlaceThreshold":20,"UseServerName":true,"UseSqlLogs":false,"WhitelistKickReason":"You are not on the whitelist."}
---
# Source: terraria/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-world-1
  labels:
    app.kubernetes.io/name: terraria-world-1
    helm.sh/chart: terraria-0.4.0
    app.kubernetes.io/instance: terraria
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName:
---
# Source: terraria/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraria-world-1
  labels:
    app.kubernetes.io/name: terraria-world-1
    helm.sh/chart: terraria-0.4.0
    app.kubernetes.io/instance: terraria
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
---
# Source: terraria/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: terraria-world-1
  labels:
    app.kubernetes.io/name: terraria-world-1
    helm.sh/chart: terraria-0.4.0
    app.kubernetes.io/instance: terraria
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
    metallb.universe.tf/allow-shared-ip: terraria-world-1
spec:
  type: LoadBalancer
  ports:
    - port: 7777
      targetPort: server
      protocol: TCP
      name: server
  selector:
    app.kubernetes.io/name: terraria-world-1
    app.kubernetes.io/instance: terraria
---
# Source: terraria/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria-world-1
  labels:
    app.kubernetes.io/name: terraria-world-1
    helm.sh/chart: terraria-0.4.0
    app.kubernetes.io/instance: terraria
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: terraria-world-1
      app.kubernetes.io/instance: terraria
  template:
    metadata:
      annotations:
        checksum/config: 4b035fb860bc2e326e3436f7b379b4840e1201e4838e88ecb97f98af520e598f
      labels:
        app.kubernetes.io/name: terraria-world-1
        app.kubernetes.io/instance: terraria
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh']
          args:
            - -c
            - |
              cp /config/config.json /world/config.json
              chmod 777 /world/config.json
          volumeMounts:
          - name: terraria-worlds
            mountPath: /world
          - name: configmap
            mountPath: /config
      serviceAccountName: terraria-world-1
      securityContext:
        null
      containers:
        - name: terraria
          args:
            - "-world"
            - "/terraria/world/worlds_World_1.wld"
          securityContext:
            null
          image: "ryshe/terraria:latest"
          imagePullPolicy: Always
          tty: false
          stdin: false
          ports:
            - name: server
              containerPort: 7777
              protocol: TCP
            - name: http
              containerPort: 7878
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          volumeMounts:
          - name: tmp
            mountPath: /terraria/world
          - name: terraria-worlds
            mountPath: /world
          resources:
            {}
      volumes:
      - name: tmp
        hostPath:
          path: /tmp/world
      - name: configmap
        configMap:
          name: terraria-world-1
      - name: terraria-worlds
        persistentVolumeClaim:
          claimName: terraria-world-1
---
# Source: terraria/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "terraria-world-1-test-connection"
  labels:
    app.kubernetes.io/name: terraria-world-1
    helm.sh/chart: terraria-0.4.0
    app.kubernetes.io/instance: terraria
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['terraria-world-1:7777']
  restartPolicy: Never
