apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"flux","namespace":"flux"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"flux"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"prometheus.io/port":"3031"},"labels":{"name":"flux"}},"spec":{"containers":[{"args":["--memcached-service=","--ssh-keygen-dir=/var/fluxd/keygen","--git-url=git@github.com:ammilam/flux-get-started","--git-branch=master","--git-path=namespaces,workloads","--git-label=flux","--git-user=ammilam","--git-email=ammilam@users.noreply.github.com","--listen-metrics=:3031"],"image":"docker.io/fluxcd/flux:1.20.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/api/flux/v6/identity.pub","port":3030},"initialDelaySeconds":5,"timeoutSeconds":5},"name":"flux","ports":[{"containerPort":3030}],"readinessProbe":{"httpGet":{"path":"/api/flux/v6/identity.pub","port":3030},"initialDelaySeconds":5,"timeoutSeconds":5},"resources":{"requests":{"cpu":"50m","memory":"64Mi"}},"volumeMounts":[{"mountPath":"/etc/fluxd/ssh","name":"git-key","readOnly":true},{"mountPath":"/var/fluxd/keygen","name":"git-keygen"}]}],"nodeSelector":{"beta.kubernetes.io/os":"linux"},"serviceAccountName":"flux","volumes":[{"name":"git-key","secret":{"defaultMode":256,"secretName":"flux-git-deploy"}},{"emptyDir":{"medium":"Memory"},"name":"git-keygen"}]}}}}
  creationTimestamp: "2020-07-15T21:01:09Z"
  generation: 1
  name: flux
  namespace: flux
  resourceVersion: "3941093"
  selfLink: /apis/extensions/v1beta1/namespaces/flux/deployments/flux
  uid: 4ecdf870-c6de-11ea-9be3-42010a8001d3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "3031"
      creationTimestamp: null
      labels:
        name: flux
    spec:
      containers:
      - args:
        - --memcached-service=
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --git-url=git@github.com:ammilam/terraria-world-1
        - --git-branch=master
        - --git-path=namespaces,workloads
        - --git-label=flux
        - --git-user=ammilam
        - --git-email=ammilam@users.noreply.github.com
        - --listen-metrics=:3031
        image: docker.io/fluxcd/flux:1.20.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/flux/v6/identity.pub
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: flux
        ports:
        - containerPort: 3030
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/flux/v6/identity.pub
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/fluxd/ssh
          name: git-key
          readOnly: true
        - mountPath: /var/fluxd/keygen
          name: git-keygen
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: flux
      serviceAccountName: flux
      terminationGracePeriodSeconds: 30
      volumes:
      - name: git-key
        secret:
          defaultMode: 256
          secretName: flux-git-deploy
      - emptyDir:
          medium: Memory
        name: git-keygen
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-07-15T21:01:16Z"
    lastUpdateTime: "2020-07-15T21:01:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-07-15T21:01:09Z"
    lastUpdateTime: "2020-07-15T21:01:16Z"
    message: ReplicaSet "flux-7b66d7c5b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
