apiVersion: v1
kind: Deployment
metadata:
  name: flux
  namespace: default
spec:
  releaseName: flux
  chart:
    repository: https://artifactory.davita.com/artifactory/helm-charts
    name: flux
    version: 1.3.0
  values:
    git:
      # url: https://$(GIT_AUTHUSER):$(GIT_AUTHKEY)@bitbucket.davita.com/scm/ccc/k8s-flux-releases.git
      url: ssh://git@bitbucket.davita.com/ccc/k8s-flux-releases.git
      pollInterval: 1m
      user: ammilam
      email: andrewmichaelmilam@gmail.com
      branch: master
     # secretName: master-flux-gitauth-key
    clusterRole:
      create: false
    registry:
      disableScanning: true
    syncGarbageCollection:
      enabled: true
    ssh:
      known_hosts: |
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCHFax37xKX3CuXnuJtiY8YjlDwccbWL4KZWfAkEEEregoeqPBmFnvwfOkb7Zxc9v4aUQZuElZUb1k4cT5puqGGGpA/CoVDJC7MHhrJ5UjzMMtLVptY2omW0y2KVUcu/r0AEvkat0mo4f3jfE61P/w1tgdfPR5bfTdE2C+2gRwZvP91yqbKZhft1Ra5iMe0UUMMknGKXcxngWKGDynR2/35ygVSwnEcCrdyRB2kia5/HmNMYR1T3M5OL3pNm3wiVFwMJ683n+AWvAv1cxtrWuf2CnN7zyBjA07HiLa1M0hGfidUfD/v5sihAZOOQVbi3jgY4a6qeOpeSE/iFc967IHZ
    image:
      repository: dockerhub.artifactory.davita.com/fluxcd/flux
      tag: 1.19.0@sha256:736ec7fd3d8def8ea249e82fac0c4e92f64b726adbb7a01cae0e9b5b82083d5d
    serviceAccount:
      create: true
      name: flux
    rbac:
      create: false
    prometheus:
      enabled: true
      serviceMonitor:
        create: true
        interval: 30s
        scrapeTimeout: 5s