---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "terraria"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "terraria"
  namespace: "terraria"
  labels:
    app: "terraria"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "terraria"
  template:
    metadata:
      labels:
        app: "terraria"
    spec:
      containers:
      - name: "terraria-sha256-1"
        image: "gcr.io/exam-prep-285301/terraria@sha256:3d038d9cedc0db2c0e4b9dd72a6ecfeae7d7ddd5eac8b9eb8e168f66266a29fb"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "terraria-hpa-hmsm"
  namespace: "terraria"
  labels:
    app: "terraria"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "terraria"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
