git:
  url: ssh://git@github.com/ammilam/terraria-world-1.git
  path: releases
  pollInterval: 1m
  user: ammilam
  email: andrewmichaelmilam@gmail.com
  secretName: flux-ssh
  label: flux-andrew
sync:
  # use `.sync.state: secret` to store flux's state as an annotation on the secret (instead of a git tag)
  state: git
  # Duration after which sync operations time out (defaults to 1m)
  timeout: 1m
registry:
  disableScanning: false
syncGarbageCollection:
  enabled: true