kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: startup-script
  labels:
    app: startup-script
spec:
  template:
    metadata:
      labels:
        app: startup-script
    spec:
      hostPID: true
      containers:
        - name: startup-script
          image: gcr.io/exam-prep-285301/startup-script:v1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
          - name: STARTUP_SCRIPT
            value: |
              #! /bin/bash
                set -o errexit
                set -o pipefail
                set -o nounset
                #this copies down the world file from the project specific world storage bucket
                apt install wget
                mkdir /tmp/world
                wget https://storage.cloud.google.com/exam-prep-285301-us-east1-terraria-world-1/worlds_World_1.wld /tmp/world/
